import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <h1>fetch & searchParams</h1>
        <h3>Params</h3>
          <nav>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/posts">Post</Link>
          </nav>
          {children}
        </body>
      <footer><p>© 2024 my footer example@.com</p></footer>
    </html>
  );
}
